#!/usr/bin/env python3
# based on https://codeberg.org/EvanHahn/dotfiles/raw/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/emoji
import sys
import unicodedata

ranges = [(0x1F100, 0x1FAFF), (0x2600, 0x26FF), (0x2700, 0x27BF)]

for start, end in ranges:
    for cp in range(start, end):
        try:
            char = chr(cp)
            name = unicodedata.name(char, '')
            if len(sys.argv) == 1:
                print(char)
            elif sys.argv[1].lower() in name.lower():
                print(char)
        except ValueError:
            pass
