#!/usr/bin/env python3
# based on https://codeberg.org/EvanHahn/dotfiles/src/commit/843b9ee13d949d346a4a73ccee2a99351aed285b/home/bin/bin/notify
import sys
import subprocess
from datetime import datetime

title = sys.argv[1] if len(sys.argv) > 1 else "Notification"
description = sys.argv[2] if len(sys.argv) > 2 else datetime.now().isoformat()

subprocess.run(
    ["osascript", "-e", f'display notification "{description}" with title "{title}"']
)
