theme = "nord"

[editor]
line-number = "relative"
mouse = true
rulers = [120]
auto-format = true
cursorline = true
color-modes = true
bufferline = "multiple"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "⋮"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "version-control"]
right = ["diagnostics", "selections", "position-percentage", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.insert]
up = "no_op"
down = "no_op"
left = "no_op"
right = "no_op"
pageup = "no_op"
pagedown = "no_op"
home = "no_op"
end = "no_op"

[keys.normal.space]
space = "file_picker"
esc = ["collapse_selection", "keep_primary_selection"]
c = ":bc"

[keys.select]
l ={l= ":pipe ~/.config/helix/openai.py"}
