use-grammars = { only = [ "mojo" ] }

[[language]]
name = "rust"
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
roots = ["Cargo.toml", "Cargo.lock"]
# auto-format = true
# comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-servers = [
  "rust-analyzer"
]

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
command = "rustup"
args = ["run", "stable", "rust-analyzer"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}" }

[[language.debugger.templates]]
name = "binary (terminal)"
request = "launch"
completion = [ { name = "binary", completion = "filename" } ]
args = { program = "{0}", runInTerminal = true }

[[language.debugger.templates]]
name = "attach"
request = "attach"
completion = ["pid"]
args = { pid = "{0}" }

[[language.debugger.templates]]
name = "gdbserver attach"
request = "attach"
completion = [ { name = "lldb connect url", default = "connect://localhost:3333" }, { name = "file", completion = "filename" }, "pid" ]
args = { attachCommands = [ "platform select remote-gdb-server", "platform connect {0}", "file {1}", "attach {2}" ] }

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.ty]
command = "ty"
args = ["server"]

[[language]]
name = "python"
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
language-servers = [
  "ruff-lsp",
  "ty",
  "pylsp"
]
auto-format = true

[language-server.pylsp.config.pylsp.plugins]
pylint = { enabled = false }
isort = { enabled = true, profile = "black" }
ruff = { enabled = true, ignore = ["F401"], lineLength = 120 }
black = { enabled = true, line_length = 120 }
flake8 = { enabled = true, maxLineLength = 120 }
autopep8 = { enabled = false }
mccabe = { enabled = false }
pycodestyle = { enabled = false, maxLineLength = 120  }
pyflakes = { enabled = false }
yapf = { enabled = false }

# mojo installation
# hx --grammar fetch
# cd ~/.config/helix
# mkdir -p runtime/queries/mojo/
# cp -r runtime/grammars/sources/mojo/runtime/queries/mojo/* runtime/queries/mojo/
# hx --grammar build
# [language-server]
# mojo = { command = "mojo-lsp-server" }

# [[language]]
# name = "mojo"
# scope = "source.mojo"
# roots = []
# injection-regex = "mojo"
# file-types = ["mojo", "🔥"]
# comment-token = "#"
# indent = { tab-width = 4, unit = "    " }
# language-servers = [ "mojo" ]

# [[grammar]]
# name = "mojo"
# source = { git = "https://github.com/garam-kim1/tree-sitter-mojo", rev = "46f89a2a6554789d534faf56e4ce2ebb3a1a5160" }

